from langchain_core.prompts import (
  ChatPromptTemplate, MessagesPlaceholder, PromptTemplate
)

from langchain_core.output_parsers import StrOutputParser
from langchain_core.messages import AIMessage
from typing import Dict, Literal

from agent.chart.utils import run_python_fig_code
from agent.chart.prompts import *
from agent.models import gpt4

LLM = gpt4
NTRY = 10

def initialize(state: Dict, config: Dict) -> Dict:
  """ Checks for valid state input and initializes state variables"""
  name = config.get("name", "chart")
  verbose = config.get("verbose", False)
  
  if verbose:
    print("--- Initializing ---")
  
  # Check for existence of dataset 
  if config.get("df") is None:
    raise Exception("Must provide dataframe `df` in config")
  
  if state.get(f"{name}_messages") is None:
    state[f"{name}_messages"] = []
  
  # Reset debug attempts  
  state[f"{name}_ntry"] = 0
  
  return state


def route(state: Dict, config: Dict) -> Literal["debug", "summarize"]:
  """ Routes agent action to either debugger or program end """
  name = config.get("name", "chart")
  ntry = config.get("ntry", NTRY)
  
  if state.get(f"{name}_fig") is None:
    return "summarize" if state[f"{name}_ntry"] > ntry else "debug"
  else:
    return "summarize"


def generate_code(state: Dict, config: Dict) -> Dict:
  """ Provides natural language description of chart generated by agent. """
  name = config.get("name", "chart")
  df = config.get("df")[0]
  llm = config.get("llm", LLM)

  # call llm to generate figure code
  prompt = ChatPromptTemplate.from_messages([
    ("system", MAKE_CHART_CODE_PROMPT),
    MessagesPlaceholder(variable_name=f"{name}_messages"),
  ])   
  
  chain = prompt | llm | StrOutputParser()
  state["column_names"] = df.columns
  result = chain.invoke(state)
  
  # update state
  state[f"{name}_code"] = result.replace("fig.show()", "")
  state[f"{name}_ntry"] += 1
  return state


def run_code(state: Dict, config: Dict) -> Dict:
  """ Runs figure generating code block and returns result or error. """  
  name = config.get("name", "chart")
  df = config.get("df")[0]   
  
  if df is None:
    raise Exception("No active data")
  else:
    code = state[f"{name}_code"]
    result = run_python_fig_code(code, {"df": df}) 
  
    if isinstance(result, Exception):
      result = f"Failed to execute CODE:\n\n{code}.\n\nERROR: {repr(result)}"
      state[f"{name}_messages"] = [AIMessage(result, name=name)]
    else:
      state[f"{name}_messages"] = [AIMessage("SUCCESS!", name=name)]
      state[f"{name}_fig"] = result
  
    return state


def debug_code(state: Dict, config: Dict) -> Dict:
  """ Provides natural language description of chart generated by agent. """
  name = config.get("name", "chart")
  df = config.get("df")[0]
  llm = config.get("llm", LLM)

  # call llm to generate figure code
  prompt = ChatPromptTemplate.from_messages([
    ("system", DEBUG_CHART_CODE_PROMPT),
    MessagesPlaceholder(variable_name=f"{name}_messages"),
  ])   
  
  chain = prompt | llm | StrOutputParser()
  
  invoke_state = {
    "column_names":df.columns, 
    "code": state[f"{name}_code"],
    f"{name}_messages":state[f"{name}_messages"]
  }
  
  result = chain.invoke(invoke_state)

  # update state
  state[f"{name}_code"] = result.replace("fig.show()", "")
  state[f"{name}_ntry"] += 1
  return state 


def summarize_chart(state: Dict, config: Dict) -> Dict:
  """ Provides natural language description of chart generated by agent. """
  name = config.get("name", "chart")
  llm = config.get("llm", LLM)

  prompt = PromptTemplate.from_template(SUMMARIZE_CHART_PROMT)  
  chain = prompt | llm | StrOutputParser()  
  
  code = state[f"{name}_code"]
  message = state[f"{name}_messages"][-1].content
  invoke_state = {"code":code, "message": message}
  state[f"{name}_fig_summary"] = chain.invoke(invoke_state)
  return state